// 2a) create a function that uses Regular Expressions to return the number of words that begin with the letter 'h'
// DO NOT use a any traditional javascript iteration techniques
// hint: look at the example on the regex builder website

// 2b) using the logic you wrote to solve 2a, write a function that finds the longest word that begins with the 's'. Do not use regex in this function, except for whats already included in your 2a logic.

// ** your code here **


// use the following string to test your solutions:
// const randomWords = "potatoes spent new clearly track exactly start help build heavy either trunk body family meal charge once cowboy find dig plan stomach magic mud pig father simply follow while late excitement nuts adventure point lying shut tail swam riding come congress brain method aloud hay sure describe strike moment giant inside ruler correct screen page different but none belong needle from beauty arm peace daily plastic nuts court how remember lying round its where roof path to frequently why engine beyond rapidly any mail right what found pond storm realize throat gray environment door cutting dark apartment are square ocean policeman wild farm metal tight value honor military zulu fog giving mice college explore unusual more recent smell work oil steam grade heading island job screen pale crowd if bend social complex helpful game journey wagon breathe cotton get wish exciting roll reach doubt able lie valuable percent elephant north home climb cut dawn production topic kids outside wild came food tide title because spider observe tobacco cowboy series come lesson hair tube high pink biggest basic unknown speed closer missing oil account task piece breathe canal potatoes chamber should successful frame source sad given born stood hung flame grain primitive topic port happy should pan with increase themselves honor finish angry ruler sweet therefore secret second safety happily voice doing perfect pound gave report occasionally unusual twenty exciting excellent positive drop help free fresh sang position early family steep bowl whether captured belt weigh locate touch into separate circle explanation stomach unusual education particularly mark molecular help environment pot muscle melted onto modern partly trouble single in back wrapped perhaps wall prevent upon escape fallen toward century feel ear food more tide fall follow force split swing least buffalo walk brief successful word brush strong outline garage each chest happened badly heavy nation last clothes worker been visitor accurate daily left onto earn discuss strike slave foreign each medicine herself example field helpful military became deeply claws getting thumb down did think opposite condition never thus wore softly affect movement motion greater softly tail owner label independent everyone asleep store substance success_success_success log sent fast leather rose zoo right stairs music different fat sense parallel higher try level law couple planet team outside summer free all mile sometime baseball suggest if excited parts entire master shelf"
